name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - ['3.8', '3.11']

    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install dependencies
      run: pip install -r requirements/ci.txt

    - name: Run Tests
      run: pycodestyle . --max-line-length=419 # TODO 419 --> 120
